
import java.util.Iterator;
import java.util.LinkedList;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author joseluis
 */
public class exa extends javax.swing.JFrame {

    boolean be1 = false, be2 = false, be3 = false, be4 = false, be5 = false, be6 = false, be7 = false, be8 = false, be9 = false, be10 = false, be11 = false, be12 = false;
    String ms[] = {"ImprimeMensaje", "ImprimeAlerta"};

    /**
     * Creates new form exa
     */
    public exa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("mensaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton1)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String texto = t1.getText(), cad = "", aux = "";
        LinkedList lista = new LinkedList();
        StringTokenizer token = new StringTokenizer(texto);
        while (token.hasMoreTokens()) {
            aux = token.nextToken();
            cad += aux + "\n";
            lista.add(aux);
        }
        Iterator iter = lista.iterator();
        while (iter.hasNext()) {
            validar_men(iter.next().toString());
        }
        System.out.println("be1=" + be1 + "  be2=" + be2 + "  be3=" + be3 + "\nbe4=" + be4 + "  be5=" + be5+ "  be6=" + be6+ "  be7=" + be7);
        be1 = false;
        be2 = false;
        be3 = false;
        be4 = false;
        be5 = false;
        be6 = false;
        be7 = false;
        be8 = false;
        be9 = false;
        be10 = false;
        be11 = false;
        be12 = false;
    }//GEN-LAST:event_jButton1ActionPerformed
    boolean validar_men(String palabra) {
        System.out.println("" + palabra);
        if (!be1) {
            for (int i = 0; i < ms.length; i++) {
                if (palabra.equals(ms[i])) {
                    System.out.println("1-" + palabra);
                    be1 = true;
                }
            }
        }
        if (be1) {
            if (palabra.equals("(")) {
                System.out.println("2-" + palabra);
                be2 = true;
            }
        }
        /*if (be2) {
            int a = palabra.length();            
            if (palabra.charAt(0)== 34 && palabra.charAt(a-1) == 34) {
                System.out.println("3-" + palabra);
                be3 = true;
            }
        }*/
        if (be2) {
            int a = palabra.length();            
            if (palabra.charAt(0)== 34) {
                System.out.println("3-" + palabra);
                be3 = true;
                be2=true;
            }
        }
        if (be3) {
            int a = palabra.length();            
            if (palabra.charAt(a-1)== 34) {
                System.out.println("4-" + palabra);
                be4 = true;
            }
        }
        if (be4) {
            if (palabra.equals(")")) {
                be7=true;
            }
        }
        
        if (be4) {
            if (palabra.equals("+")) {
                System.out.println("4-"+palabra);
                be5=true;
            }
        }
        
        if (be5) {
            if (palabra.charAt(0) >= 65 && palabra.charAt(0) <= 90
             || palabra.charAt(0) >= 97 && palabra.charAt(0) <= 122){
                for (int i = 0; i < palabra.length(); i++) {
                    if (palabra.charAt(i) >= 65 && palabra.charAt(i) <= 90
                     || palabra.charAt(i) >= 97 && palabra.charAt(i) <= 122
                     || palabra.charAt(i)>=48 && palabra.charAt(i)>=57){
                        System.out.println("5l-"+palabra.charAt(i)); 
                        be6=true;
                    }
                    else{
                        be6=false;
                    }
                }
            }
            if (Character.isDigit(palabra.charAt(0)) == true) { 
                for (int i = 0; i <palabra.length(); i++) {
                    if (Character.isDigit(palabra.charAt(i)) == true) {
                        System.out.println("5n-"+palabra.charAt(i)); 
                        be6=true;
                    }else{
                        be6=false;
                    }
                }
            }
        }
        if (be6) {
            if (palabra.equals("+")) {
                be2=false;
            }
            
        }
        if (be6) {
            if (palabra.equals(")")) {
                be7=true;
            }
        }
        if (be7) {
            if (palabra.equals(";")) {
                be8=true;
            }
        }
        
        
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
